[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }

leptos = { version = "0.7", features = ["csr"] }
leptos_router = { version = "0.7" }
leptos_meta = { version = "0.7" }
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"


[[bin]]
name = "frontend"
path = "src/main.rs"
