[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "backend"
path = "src/main.rs"

[[bin]]
name = "admin-cli"
path = "src/bin/admin-cli.rs"
[dependencies]
# Workspace shared
shared = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }

# Async runtime
tokio = { version = "1", features = ["full"] }

# Web framework
axum = { version = "0.7", features = ["ws", "multipart", "macros"] }
tower-http = { version = "0.5", features = ["cors", "fs", "limit", "set-header"] }
tower = { version = "0.4" }

# Database ORM
sea-orm = { version = "1", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
rust_decimal = { version = "1", features = ["serde-with-float"] }

# Auth & Security
argon2 = "0.5"
jsonwebtoken = "9"
totp-rs = { version = "5", features = ["qr"] }
aes-gcm = "0.10"
base64 = "0.22"
rand = "0.8"

# BCH Wallet
bip39 = "2"
bitcoin = { version = "0.31", features = ["serde"] }
reqwest = { version = "0.12", features = ["json"] }

# Real-time
redis = { version = "0.25", features = ["tokio-comp", "connection-manager"] }
tokio-cron-scheduler = "0.10"

# Validation & Utils
lettre = { version = "0.11", features = ["tokio1", "tokio1-native-tls"] }
validator = { workspace = true }
uuid = { version = "1", features = ["v4", "serde"] }
dotenvy = "0.15"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
async-trait = "0.1"
sqids = "0.4.2"
infer = "0.22.0"

ethers = "2.0" # For ethereum interaction
futures-util = "0.3.33"
eyre = "0.6.12"
hex = "0.4.3"

[dev-dependencies]
mockall = "0.15.0"
sea-orm = { version = "1", features = ["mock"] }
rust_decimal_macros = "1.40.0"


